### Створити новий план
POST http://localhost:3000/api/travel-plans
Content-Type: application/json

{
  "title": "Мій перший план подорожі",
  "budget": 1000
}

### Отримати всі плани (щоб дізнатися ID та версію)
GET http://localhost:3000/api/travel-plans

### 1. Додаємо першу локацію (має отримати order_number: 1)
POST http://localhost:3000/api/travel-plans/7820481b-62d8-44c6-8bbd-6952172d6fb0/locations
Content-Type: application/json

{
  "name": "Париж",
  "notes": "Ейфелева вежа"
}Locations

### 2. Додаємо другу локацію (має отримати order_number: 2 автоматично)
POST http://localhost:3000/api/travel-plans/7820481b-62d8-44c6-8bbd-6952172d6fb0/locations
Content-Type: application/json

{
  "name": "Рим",
  "notes": "Колізей"
}

### 3. Перевірка Оптимістичного блокування (Проблема 1)
# Спробуй надіслати цей запит із версією, яка НЕ збігається з БД (наприклад, 999)
# Ти маєш отримати 409 Conflict
PUT http://localhost:3000/api/travel-plans/7820481b-62d8-44c6-8bbd-6952172d6fb0
Content-Type: application/json

{
  "title": "Спроба зламати версію",
  "version": 999
}